[package]
name = "nscompress"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libc = { version = "0.2", default-features = false }

[profile.release]
strip = true
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
